workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios
    scripts:
      - name: Move into Flutter project directory
        script: |
          cd hello_world

          echo "Running flutter pub get..."
          flutter pub get

          echo "Decoding and importing certificate..."
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          echo $PROVISION_PROFILE_BASE64 | base64 --decode > profile.mobileprovision

          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

          echo "Building Flutter iOS app..."
          flutter build ios --release --no-codesign

          echo "Archiving app with xcodebuild..."
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -archivePath build/Runner.xcarchive \
                     archive \
                     -allowProvisioningUpdates

          echo "Exporting .ipa file..."
          xcodebuild -exportArchive \
                     -archivePath build/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath build

    artifacts:
      - hello_world/build/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        api_issuer: $APP_STORE_CONNECT_API_ISSUER
        apple_id: $APPLE_ID
        app_identifier: com.ficode.helloworld
        ipa_path: hello_world/build/Runner.ipa
