workflows:
  ios-app-store:
    name: iOS App Store Build
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.ficode.helloworld"
        DEVELOPMENT_TEAM: "8QF5HJCTR8"   # Replace with your actual Team ID
      xcode: 16.3
      cocoapods: default
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build and archive iOS app
        script: |
          flutter build ios --release --no-codesign

          xcodebuild clean

          xcodebuild archive \
            -workspace ios/$XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath build/ios/archive.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM

      - name: Export IPA
        script: |
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <true/>
            <key>teamID</key>
            <string>$DEVELOPMENT_TEAM</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/ios/archive.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios/output \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/output/*.ipa
      - build/ios/archive.xcarchive
