workflows:
  ios-workflow:
    name: iOS HelloWorld Build
    environment:
      vars:
        APP_ID: "com.ficode.helloworld"
        BUNDLE_ID: "com.ficode.helloworld"
        APP_NAME: "HelloWorld"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        DEVELOPMENT_TEAM: "8QF5HJCTR8"
        CODE_SIGN_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "ficode_helloworld_distribution"
      flutter: stable
      xcode: latest
      cocoapods: default
      signing:
        provisioning_profiles:
          com.ficode.helloworld: ficode_helloworld_distribution
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Set up keychain and certificates
        script: |
          KEYCHAIN_PASSWORD="codemagic"
          security create-keychain -p "$KEYCHAIN_PASSWORD" ios-build.keychain
          security default-keychain -s ios-build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" ios-build.keychain
          security set-keychain-settings ios-build.keychain

          # Import certificate (make sure it's uploaded in the CodeMagic UI as secure ENV VAR)
          echo $CM_CERTIFICATE | base64 --decode > signing_certificate.p12
          security import signing_certificate.p12 -k ios-build.keychain -P $CM_CERTIFICATE_PASSWORD -T /usr/bin/codesign

          # Set key partition list (fixes macOS 13+ signing issues)
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" ios-build.keychain
      - name: Build iOS release
        script: |
          flutter build ios --release \
            --no-codesign \
            --build-name=1.0.0 \
            --build-number=1
          
          xcodebuild -workspace ios/$XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath build/ios/archive.xcarchive \
            archive \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER"
          
          xcodebuild -exportArchive \
            -archivePath build/ios/archive.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/out
    artifacts:
      - build/ios/out/*.ipa
