workflows:
  ios-workflow:
    name: iOS TestFlight Build and Upload
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: "com.ficode.helloworld"
        CERTIFICATE_PASSWORD: Encrypted
      groups:
        - ios2
    scripts:
      - name: change directory to hello world
        script: cd hello_world/
      - name: Flutter pub get
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ios --release
      - name: Build IPA with xcodebuild
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/Runner.xcarchive archive

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
