workflows:
  ios-workflow:
    name: iOS Manual Signing Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        CERTIFICATE_PASSWORD: Encrypted
      groups:
        - ios2
    scripts:
      - name: Decode and install signing certificate and provisioning profile
        script: |
          echo "ðŸ” Setting up certificate and provisioning profile"

          # Decode certificate and profile
          echo $CERTIFICATE_BASE64 | base64 --decode > signing_certificate.p12
          echo $PROVISIONING_PROFILE_BASE64 | base64 --decode > profile.mobileprovision

          # Create and set up keychain
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import signing_certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

          # Extract UUID and copy profile
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" /dev/stdin <<< $(security cms -D -i profile.mobileprovision))
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision

          echo "âœ… Provisioning profile installed with UUID: $PROFILE_UUID"
          ls -l ~/Library/MobileDevice/Provisioning\ Profiles/
        working_directory: hello_world

      - name: Install dependencies
        script: flutter pub get
        working_directory: hello_world

      - name: Build Flutter iOS app without signing
        script: flutter build ios --release --no-codesign
        working_directory: hello_world

      - name: Archive the app with manual signing
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/Runner.xcarchive \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="ficode_helloworld_distribution" \
            DEVELOPMENT_TEAM="86L854D6DS" \
            CODE_SIGN_IDENTITY="Apple Distribution"
        working_directory: hello_world

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/ios/ipa
        working_directory: hello_world

    artifacts:
      - build/ios/ipa/*.ipa
