workflows:
  ios-release-build:
    name: iOS Release Build
    environment:
      vars:
        BUNDLE_ID: "com.ficode.helloworld"
        DEVELOPMENT_TEAM: "8QF5HJCTR8"
        CODE_SIGNING_IDENTITY: "Apple Distribution"
        PROVISIONING_PROFILE_NAME: "ficode_helloworld_distribution"
      flutter: stable
      xcode: 16.3
    scripts:
      - name: Set up keychain and provisioning
        script: |
          # Save certificate and provisioning profile to files
          echo $CERTIFICATE_BASE64 | base64 --decode > signing_certificate.p12
          echo $PROVISIONING_PROFILE_BASE64 | base64 --decode > profile.mobileprovision

          # Create custom keychain and import certificate
          security create-keychain -p "pass" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "pass" build.keychain
          security import signing_certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "pass" build.keychain

          # Copy provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          UUID=$(grep -aA1 UUID profile.mobileprovision | grep -io "[-A-F0-9]\{36\}")
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision

      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get

      - name: Build archive
        script: |
          flutter build ios --release --no-codesign

          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $PWD/build/Runner.xcarchive \
            archive CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            PROVISIONING_PROFILE_SPECIFIER=$PROVISIONING_PROFILE_NAME \
            CODE_SIGN_IDENTITY="$CODE_SIGNING_IDENTITY"

      - name: Generate ExportOptions.plist
        script: |
          cat > ios/ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>$DEVELOPMENT_TEAM</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$BUNDLE_ID</key>
              <string>$PROVISIONING_PROFILE_NAME</string>
            </dict>
            <key>destination</key>
            <string>export</string>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $PWD/build/ipa

    artifacts:
      - build/ipa/*.ipa
