workflows:
  ios-workflow:
    name: iOS Build & Archive
    max_build_duration: 60
    environment:
      vars:
        TEAM_ID: 8QF5HJCTR8
        APP_IDENTIFIER: com.ficode.helloworld
        PROVISIONING_PROFILE_SPECIFIER: ficode_helloworld_distribution
        EXPORT_METHOD: app-store  # Change to 'ad-hoc' or 'development' as needed
      flutter: stable
      xcode: latest
      cocoapods: default
      signing:
        ios:
          certificate: EncryptedIOSCertificate.p12
          certificate_password: $CERT_PASSWORD
          provisioning_profile: $PROVISIONING_PROFILE_SPECIFIER

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          pod install --project-directory=ios

      - name: Build and archive iOS app
        script: |
          set -o pipefail
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            clean archive | tee xcodebuild.log | xcbeautify

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/exported | tee export.log | xcbeautify

      - name: Publish artifacts
        script: |
          echo "App archived and exported successfully."

    artifacts:
      - $CM_BUILD_DIR/exported/*.ipa
      - ios/Runner.xcarchive
