workflows:
  ios-workflow:
    name: iOS App Store Build with Automatic Signing
    integrations:
      app_store_connect: BSM CI/CD Pipeline   # Replace with your integration ID from Codemagic UI

    environment:
      vars:
        BUNDLE_ID: "com.ficode.helloworld"
      xcode: latest
      cocoapods: default
      flutter: stable
      groups:
        - ios
      node: 16

    scripts:
      - name: Set up keychain and certificates
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE
          keychain add-certificates

      - name: Flutter build ios
        script: |
          flutter clean
          flutter pub get
          flutter build ios --release --no-codesign

      - name: Archive app
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive.xcarchive \
            -allowProvisioningUpdates \
            -sdk iphoneos \
            archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
