workflows:
  ios-workflow:
    name: iOS HelloWorld Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "hello_world"
      groups:
        - ios  # This is your variable group with the base64 encoded .p12 and .mobileprovision
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS app for release (signed)
        script: |
          flutter build ios --release

    artifacts:
      - build/ios/ipa/*.ipa

    code_signing:
      distribution_type: app_store
      bundle_identifier: com.ficode.helloworld
      certificate_url: Encrypted(base64 content of your p12)
      certificate_password: $CERTIFICATE_PASSWORD
      provisioning_profile_url: Encrypted(base64 content of your .mobileprovision)
      signing_certificate: Apple Distribution

    publishing:
      email:
        recipients:
          - your-email@example.com
