workflows:
  ios-workflow:
    name: iOS Build & Upload
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios # Contains CERTIFICATE_BASE64, CERTIFICATE_PASSWORD, PROVISION_PROFILE_BASE64
      vars:
        APP_ID: com.ficode.helloworld
        PROVISIONING_PROFILE_NAME: ficode_helloworld_distribution
        TEAM_ID: H74K77RF8V

    integrations:
      app_store_connect: appstore-connect # <-- Must match integration name in Codemagic UI

    scripts:
      - name: Build and export .ipa
        script: |
          cd hello_world

          echo "Installing dependencies..."
          flutter pub get

          echo "Decoding and importing certificate..."
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          echo $PROVISION_PROFILE_BASE64 | base64 --decode > profile.mobileprovision

          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

          echo "Building Flutter iOS app..."
          flutter build ios --release

          echo "Archiving app with xcodebuild..."
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -archivePath build/Runner.xcarchive \
                     archive

          echo "Exporting .ipa for App Store..."
          xcodebuild -exportArchive \
                     -archivePath build/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath build/ios/ipa

    artifacts:
      - hello_world/build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
