workflows:
  ios-workflow:
    name: iOS Build and Upload
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios2  # Make sure this group contains the required environment variables
    scripts:
      - name: Move into Flutter project directory
        script: |
          cd hello_world

          echo "Running flutter pub get..."
          flutter pub get

          echo "Decoding and importing certificate..."
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          echo $PROVISION_PROFILE_BASE64 | base64 --decode > profile.mobileprovision

          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

          echo "Building iOS IPA..."
          flutter build ipa --release --export-options-plist=ExportOptions.plist

      - name: Upload to App Store Connect
        script: |
          echo "Creating private key from base64..."
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | base64 --decode > AuthKey.p8

          echo "Uploading .ipa to App Store Connect..."
          xcrun altool --upload-app \
            --type ios \
            --file "hello_world/build/ios/ipa/Runner.ipa" \
            --apiKey "$APP_STORE_CONNECT_KEY_ID" \
            --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID"

    artifacts:
      - hello_world/build/ios/ipa/Runner.ipa
