workflows:
  ios-workflow:
    environment:
      groups:
        - ios
    scripts:
      - |
        echo $CERTIFICATE_BASE64 | base64 --decode > ~/certificate.p12
        echo $PROVISION_PROFILE_BASE64 | base64 --decode > ~/profile.mobileprovision

        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain

        security import ~/certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp ~/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

        security set-keychain-settings -t 3600 -u build.keychain

      - flutter build ios --release --no-codesign  # or your flutter build command
