workflows:
  flutter-workflow:
    name: Build hello_world app
    environment:
      working_directory: hello_world
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build iOS IPA
        script: flutter build ios --release --no-codesign

      - name: Build Android APK
        script: flutter build apk --release

    artifacts:
      - hello_world/build/app/outputs/flutter-apk/app-release.apk
      - hello_world/build/ios/ipa/*.ipa
