workflows:
  ios-workflow:
    environment:
      flutter: stable
      xcode: latest
      vars:
        CERTIFICATE_PASSWORD: Encrypted
      groups:
        - ios2
    scripts:
      - name: Setup signing cert and profile
        script: |
          echo $CERTIFICATE_BASE64 | base64 --decode > signing_certificate.p12
          echo $PROVISIONING_PROFILE_BASE64 | base64 --decode > profile.mobileprovision

          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import signing_certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

          PROFILE_UUID=$(security cms -D -i profile.mobileprovision | plutil -extract UUID xml1 -o - - | xmllint --xpath "string(//string)" -)
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision
        working_directory: hello_world

      - name: Install dependencies
        script: flutter pub get
        working_directory: hello_world

      - name: Build Flutter iOS app without signing
        script: flutter build ios --release --no-codesign
        working_directory: hello_world

      - name: Archive the app with manual signing
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="ficode_helloworld_distribution" \
            DEVELOPMENT_TEAM="86L854D6DS"
        working_directory: hello_world

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa
        working_directory: hello_world

    artifacts:
      - build/ios/ipa/*.ipa
